### ISSUE TITLE
Active session listing

### ISSUE THREAD

**Issue by henoja** [tohalla/isla#47]
Active session listing in active session feed. Location main page/view. Seach tool included.

**Comment by tohalla** [comment]
list active sessions directly or just courses with an active session?

**Comment by henoja** [comment]
All active sessions listed. Can be categorized by faculties such as:

Tietotekniikan erikoiskysymyksiä
Ohjelmointi
----
Semantiikka
Englannin kielen historia
----
Markkinoinnin perusteet
Kansainvälinen liiketoiminta
International Business Etiquet
Export operations

Color/font or alternative way to highlight active sessions in different faculties, e.g technlogy blue, business red, philosophy green et al.

**Comment by tohalla** [comment]
close as duplicate of #46
