### ISSUE TITLE
Session export to PDF

### ISSUE THREAD

**Issue by henoja** [tohalla/isla#50]
Export to PDF file type

**Comment by tohalla** [comment]
What should output file contain? Any specific template, or just bolded titles and content beneath those?

**Comment by henoja** [comment]
No need for specific template in this point, just clear framework is enough. Bolded titles, empty space between columns/rows etc.

**Comment by henoja** [comment]
Content would be at least following: content (comment + answers), scores ("likes") if exists, timestamp, lecture/course name. Other?
