### ISSUE TITLE
Visitor view

### ISSUE THREAD

**Issue by Masce** [tohalla/isla#52]
If visitors can not comment on lecture view, should there be some info about that? Now you can see the same lecture view and even write comments on comment field although they do not list on lecture view. Should comment field be hidden from visitors so that they can only see the comment listing? Or should there be an info text, for example: "For commenting, you can register here" (link)?

**Comment by tohalla** [comment]
Currently all participants can add comments in an active lecture. Weren't you able to leave a comment without authenticating?

When a lecture is deactivated, the comment bar (the whole yellow area at the top) will be removed. However, this is not yet implemented

**Comment by Masce** [comment]
Yesterday while testing, I couldn't comment without authenticating. Now it seems that all the comments come in double when logged in as admin. I can comment without authentication now, and comment listing is ok, but the same view as admin lists all the comments as double.

**Comment by Masce** [comment]
When I leave the room and come back again, the comment listing is okay, but when I write a new comment as admin, it comes out double. Same view as visitor is okay, but when I write a comment as visitor, it also comes out double on the admin view.

**Comment by tohalla** [comment]
Unable to reproduce. What browser are you using? 

I also noticed that I'm unable to use the websocket connection on private mode (safari). This would explain the problem with comments not appearing.

**Comment by Masce** [comment]
I use both Safari and Chrome. Now listing is okay and comments don't come double. But now I can't erase or check comments as read. Liking works fine. I checked that admin is a moderator and started new lecture, liking works fine but I can't erase comments or check them out as read when signed in as admin.

**Comment by henoja** [comment]
In future purposes, add screenshot (e.g. via link) here to explain further active issue if possible.

**Comment by tohalla** [comment]
Likely resolved. There were some issues with ws connection, which may have caused the problem
