### ISSUE TITLE
Lower tab

### ISSUE THREAD

**Issue by Masce** [tohalla/isla#55]
With lower tab I mean the front page tab where's for example "Check us out on GitHub".

Will there be more stuff? I mean for example, the introductions, FAQs, terms of use, contact details etc. could be handy.

**Comment by Masce** [comment]
Introductions could also be on lecture view. Maybe on the right upper corner when "Return" is on the left. Could help out new users.

**Comment by tohalla** [comment]
Do you mean instructions? @henoja and I will add some sort of introduction post  to front page, which would contain a link to the instructions. Would this be sufficient?

**Comment by henoja** [comment]
Info goes to front page, more than enough blank space available (see white bg area). Some links (Github repo etc) goes to footer.
