### ISSUE TITLE
Session calendar translations for session expire date

### ISSUE THREAD

**Issue by henoja** [tohalla/isla#66]
Session calendar translations for session expire date. Finnish and Swedish needed, now English default language in all.

**Comment by tohalla** [comment]
Add translations to general.json, should be found under calendar: {}. Assigned to @henoja, will look at this when translations added

**Comment by henoja** [comment]
Not able to locate calendar translations @tohalla, able to collaborate?

**Comment by tohalla** [comment]
create a new key with name "calendar" to [general.json](https://github.com/tohalla/isla/blob/development/src/main/webapp/i18n/en/general.json). Values must be separated with commas (Excluding the last one). e.g. "calendar": {"day": "Day", "month": "Month", "year": "Year"}
